# -*- coding: utf-8 -*-
"""LeitordePDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrXZsSwqUfn1rtwScVhkNPZmYybJPcjF
"""

!pip install PyPDF2
#Biblioteca usada para manipular arquivos em PDF.

from google.colab import files
#Importa o módulo que permite lidar com arquivos no Collab.
upload = files.upload()
#Abre uma janela para você escolher e enviar os arquivos do seu computador e armazena esses arquivos em uma variável.

import os
#Biblioteca para interagir com funcionalidades do sistem operacional
import PyPDF2
#Biblioteca para ler aquivos em PDF
caminho = "dados.pdf"
#Adicionar o arquivo a uma variavel, para ultilizar no codigo

if os.path.exists(caminho):#verificar se o arquivo existe no caminho informado
    arquivo = open(caminho, "rb") #varivel que armazena o conteudo em modo binario
    leitor_pdf = PyPDF2.PdfReader(arquivo)#lê o conteudo dentro do pdf

    numeros = []# cria um lista vazia
#dentro de uma estrutura condicional
    for pagina in leitor_pdf.pages:# laço para percorrer toda a pagina do pdf
        texto = pagina.extract_text()#Extrai o texto e armazena na variavel
        linhas = texto.split('\n')#divide o texto em linhas quando encontra uma quebra de linha

        for linha in linhas:#laço de repetição
            if linha.strip().isdigit():#remover espaços em branco no inicio e no fim da stringe ver se os numeros sao inteiros e positivos
                numeros.append(int(linha.strip()))#adiciona o valor convertido em inteiro a lista numeros.

    arquivo.close()#fecha o arquivo

    if len(numeros) > 0:#verifica se tem numero
        numeros.sort()#ordenar crescente
        soma = sum(numeros) #soma os numeros
        media = soma / len(numeros)#conta quantos numeros tem na lista e divide pela soma deles

        if len(numeros) % 2 == 0: # verifica se a quantidade de numeros é par
            meio = len(numeros) // 2 #calcula o indice do meio da lista
            mediana = (numeros[meio - 1] + numeros[meio]) / 2#pega os dois elementos centrais da lista e divide por 2
        else:
            mediana = numeros[len(numeros) // 2]#encontra o indice do valor central, como é uma quantide impar ele é a median

        print("Números encontrados:", numeros)
        print("Média:", media)
        print("Mediana:", mediana)
        print("Soma:", soma)
        print("Maior valor:", max(numeros))#funcao que retorna maior valor, min retorna o menor.
        print("Menor valor:", min(numeros))#mostra os resultados na tela
    else:
        print("O arquivo está vazio ou não contém números válidos.")#se nao tiver nada dentro do arquivo imprime a frase.
else:
    print("Arquivo não encontrado.")# Se nãa achar arquivo, imprime essa frase
